Repository fanscoffee/Web4.0, pull requests merged in 2025-02, with the labels that each got.

#16 Javierg
  .gitignore
  app/components/Footer.tsx
  app/layout.tsx
  app/sitemap.tsx
  app/sitemap/page.tsx
  package-lock.json
Labels: enhancement

#18 Agrego robotx.txt y metadatos de esquema en pagina de inicio
  app/page.tsx
  public/robots.txt
Labels: enhancement

#19 add: robots.ts to autogenerate robots.txt
  app/robots.ts
Labels: enhancement

#20 fix: title and mobile logo
  app/components/Header.tsx
  app/layout.tsx
  app/page.tsx
Labels: bug

#21 Develop
  app/components/Header.tsx
  app/layout.tsx
  app/page.tsx
  app/robots.ts
  public/robots.txt
Labels: bug

#23 Add schema.org data and fix alt in img
  app/components/ParallaxComponent.tsx
  app/layout.tsx
  app/page.tsx
Labels: bug, enhancement

#24 Agrego Schema.org y alt a las imagenes
  app/components/ParallaxComponent.tsx
  app/layout.tsx
  app/page.tsx
Labels: bug, enhancement
